### ISSUE TITLE
Login Failed with Unhandle Error Event

### ISSUE THREAD

**Issue by kkruups** [watilde/gistjs#6]
## Issue
1.After entering login following error indicated
(steps to recreate:    gistjs --login  (enter username and password when prompted, then hit enter)

Environment:
Win7 SP1
Behind  Proxy

## Error Indicated:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT X.X.X.X:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by kkruups** [comment]
Additional Info:  I presume related to proxy, may need to allow user to set proxy during login or use existing proxy settings to allow login to succeed.   I saw a related error which was resolved by setting proxy in node app:

http://stackoverflow.com/questions/32292390/etimeout-on-running-sample-js-of-versionone-javascript-sdk
